---
version: '2'

services:
  vol1:
    build: vol1

  emacs:
    build: emacs
    hostname: dev-emacs
    volumes_from:
      - vol1
    volumes:
      - ~/work:/work
      - ~/.ssh:/home/docker/.ssh
    security_opt:
      - seccomp:unconfined
    networks:
      mynet:
        ipv4_address: 172.25.0.11

  ruby01:
    build: ruby
    hostname: ruby01
    volumes_from:
      - vol1
    volumes:
      - ~/work:/work
      - ~/.ssh:/home/docker/.ssh
    networks:
      mynet:
        ipv4_address: 172.25.0.21

  stage01:
    build: ruby
    hostname: stage01
    volumes_from:
      - vol1
    volumes:
      - ~/work:/work
      - ~/.ssh:/home/docker/.ssh
    networks:
      mynet:
        ipv4_address: 172.25.0.51

  python01:
    build: python
    hostname: python01
    volumes_from:
      - vol1
    volumes:
      - ~/work:/work
      - ~/.ssh:/home/docker/.ssh
    networks:
      mynet:
        ipv4_address: 172.25.0.61

  php01:
    build: php
    hostname: php01
    volumes_from:
      - vol1
    volumes:
      - ~/work:/work
      - ~/.ssh:/home/docker/.ssh
    networks:
      mynet:
        ipv4_address: 172.25.0.71

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    volumes_from:
      - vol1
    networks:
      mynet:
        ipv4_address: 172.25.0.101

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24


    
