---
version: '2'

services:
  vol1:
    build: vol1

  emacs:
    build: emacs
    volumes_from:
      - vol1
    volumes:
      - ~/work:/work
    security_opt:
      - seccomp:unconfined
    networks:
      mynet:
        ipv4_address: 172.25.0.11

  ruby:
    build: ruby
    volumes_from:
      - vol1
    volumes:
      - ~/work:/work
    links:
      - mysql
    networks:
      mynet:
        ipv4_address: 172.25.0.21

  stage:
    build: ruby
    volumes_from:
      - vol1
    volumes:
      - ~/work:/work
    links:
      - mysql
    networks:
      mynet:
        ipv4_address: 172.25.0.51

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '13306:3306'
    volumes_from:
      - vol1
    networks:
      mynet:
        ipv4_address: 172.25.0.101

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24


    
